#!/usr/bin/python2
import logging
import ossipee

logging.basicConfig(level=logging.INFO)


class App(ossipee.Application):

    description = 'Add a new host to the current plan.'

    def get_parser(self):
        parser = super(App, self).get_parser()
        parser.add_argument('host', nargs='?', default='deleteme',
                            help='New Host to add"')
        return parser

    def create_host(self):
        self.plan.add_host(self.args.host)
        self.build_work_item_list([
            lambda session, plan: ossipee.NovaServer(session,
                                                     plan,
                                                     self.args.host),
            lambda session, plan: ossipee.FloatIP(session,
                                                  plan,
                                                  self.args.host),
            ossipee.Inventory
        ]).create()


App().create_host()
