---
- hosts: ipa_clients
  remote_user: "{{cloud_user}}"
  sudo: yes
  name: install-rdo
  tasks:
  - yum: name=cloud-init state=absent
  - yum: name=* state=latest
  - yum: name=ipa-client state=latest
  - command: sed -i "s/^nameserver .*/nameserver {{ nameserver }}/g" /etc/resolv.conf
  - command: ipa-client-install -U -p admin@{{ ipa_realm }} -w {{ipa_admin_user_password }} --force --domain {{ ipa_domain }} --force-ntpd
