---
- hosts: ipa
  remote_user: "{{cloud_user}}"
  sudo: yes
  name: install-ipa
  tasks:
  - yum: name=* state=latest
  - yum: name=bind-dyndb-ldap,ipa-server state=latest

  - command: ipa-server-install -U -r {{ ipa_realm }} -p {{ ipa_server_password }} -a {{ ipa_admin_user_password }} -d  {{ ipa_domain }} --setup-dns --forwarder {{ ipa_forwarder }}   --ip-address={{ nameserver }}
